// <auto-generated />
using System;
using BoardGameLogger.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoardGameLogger.Data.Migrations
{
    [DbContext(typeof(BoardGameLoggerDbContext))]
    [Migration("20260314162231_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BoardGameLogger.Data.Models.BoardGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<int>("MaxPlayers")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.Property<int>("MinPlayers")
                        .HasColumnType("int");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("YearPublished")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.ToTable("BoardGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A competitive, medium-weight, card-driven, engine-building board game.",
                            MaxPlayers = 5,
                            MinPlayers = 1,
                            PublisherId = 1,
                            Title = "Wingspan",
                            YearPublished = 2019
                        },
                        new
                        {
                            Id = 2,
                            Description = "A cross-country train adventure in which players collect and play matching train cards to claim railway routes.",
                            MaxPlayers = 5,
                            MinPlayers = 2,
                            PublisherId = 3,
                            Title = "Ticket to Ride",
                            YearPublished = 2004
                        });
                });

            modelBuilder.Entity("BoardGameLogger.Data.Models.LoanLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BoardGameId")
                        .HasColumnType("int");

                    b.Property<string>("BorrowerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("LoanDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BoardGameId");

                    b.ToTable("LoanLogs");
                });

            modelBuilder.Entity("BoardGameLogger.Data.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "USA",
                            Name = "Stonemaier Games"
                        },
                        new
                        {
                            Id = 2,
                            Country = "France",
                            Name = "Asmodee"
                        },
                        new
                        {
                            Id = 3,
                            Country = "USA",
                            Name = "Days of Wonder"
                        });
                });

            modelBuilder.Entity("BoardGameLogger.Data.Models.BoardGame", b =>
                {
                    b.HasOne("BoardGameLogger.Data.Models.Publisher", "Publisher")
                        .WithMany("BoardGames")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("BoardGameLogger.Data.Models.LoanLog", b =>
                {
                    b.HasOne("BoardGameLogger.Data.Models.BoardGame", "BoardGame")
                        .WithMany("LoanLogs")
                        .HasForeignKey("BoardGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardGame");
                });

            modelBuilder.Entity("BoardGameLogger.Data.Models.BoardGame", b =>
                {
                    b.Navigation("LoanLogs");
                });

            modelBuilder.Entity("BoardGameLogger.Data.Models.Publisher", b =>
                {
                    b.Navigation("BoardGames");
                });
#pragma warning restore 612, 618
        }
    }
}
