// <auto-generated />
using System;
using BoardGameLogger.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoardGameLogger.Data.Migrations
{
    [DbContext(typeof(BoardGameLoggerDbContext))]
    [Migration("20260316183924_AddedMoreSeeding")]
    partial class AddedMoreSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BoardGameLogger.Data.Models.BoardGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<int>("MaxPlayers")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.Property<int>("MinPlayers")
                        .HasColumnType("int");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("YearPublished")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.ToTable("BoardGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Bird collection and engine building. Very relaxing.",
                            MaxPlayers = 5,
                            MinPlayers = 1,
                            PublisherId = 1,
                            Title = "Wingspan",
                            YearPublished = 2019
                        },
                        new
                        {
                            Id = 2,
                            Description = "Social word game where you give one-word clues.",
                            MaxPlayers = 8,
                            MinPlayers = 2,
                            PublisherId = 2,
                            Title = "Codenames",
                            YearPublished = 2015
                        },
                        new
                        {
                            Id = 3,
                            Description = "Classic train route building game across North America.",
                            MaxPlayers = 5,
                            MinPlayers = 2,
                            PublisherId = 3,
                            Title = "Ticket to Ride",
                            YearPublished = 2004
                        },
                        new
                        {
                            Id = 4,
                            Description = "War in the forest where every player has totally different rules.",
                            MaxPlayers = 4,
                            MinPlayers = 2,
                            PublisherId = 4,
                            Title = "Root",
                            YearPublished = 2018
                        },
                        new
                        {
                            Id = 5,
                            Description = "Farming simulator where you try not to starve your family.",
                            MaxPlayers = 5,
                            MinPlayers = 1,
                            PublisherId = 5,
                            Title = "Agricola",
                            YearPublished = 2007
                        },
                        new
                        {
                            Id = 6,
                            Description = "Massive dungeon crawl with a legacy campaign.",
                            MaxPlayers = 4,
                            MinPlayers = 1,
                            PublisherId = 6,
                            Title = "Gloomhaven",
                            YearPublished = 2017
                        },
                        new
                        {
                            Id = 7,
                            Description = "The sequel to Gloomhaven with even more cardboard.",
                            MaxPlayers = 4,
                            MinPlayers = 1,
                            PublisherId = 7,
                            Title = "Frosthaven",
                            YearPublished = 2023
                        },
                        new
                        {
                            Id = 8,
                            Description = "Beautiful tile-laying game about decorating a palace.",
                            MaxPlayers = 4,
                            MinPlayers = 2,
                            PublisherId = 8,
                            Title = "Azul",
                            YearPublished = 2017
                        },
                        new
                        {
                            Id = 9,
                            Description = "Cooperative game where you try to save the world from diseases.",
                            MaxPlayers = 4,
                            MinPlayers = 2,
                            PublisherId = 9,
                            Title = "Pandemic",
                            YearPublished = 2008
                        },
                        new
                        {
                            Id = 10,
                            Description = "A dice rolling game about drawing exits and routes.",
                            MaxPlayers = 6,
                            MinPlayers = 1,
                            PublisherId = 10,
                            Title = "Railroad Ink",
                            YearPublished = 2018
                        });
                });

            modelBuilder.Entity("BoardGameLogger.Data.Models.LoanLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BoardGameId")
                        .HasColumnType("int");

                    b.Property<string>("BorrowerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("LoanDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BoardGameId");

                    b.ToTable("LoanLogs");
                });

            modelBuilder.Entity("BoardGameLogger.Data.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "USA",
                            Name = "Stonemaier Games"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Czech Republic",
                            Name = "Czech Games Edition"
                        },
                        new
                        {
                            Id = 3,
                            Country = "France",
                            Name = "Days of Wonder"
                        },
                        new
                        {
                            Id = 4,
                            Country = "USA",
                            Name = "Leder Games"
                        },
                        new
                        {
                            Id = 5,
                            Country = "Germany",
                            Name = "Lookout Games"
                        },
                        new
                        {
                            Id = 6,
                            Country = "USA",
                            Name = "Cephalofair Games"
                        },
                        new
                        {
                            Id = 7,
                            Country = "USA",
                            Name = "Childreans"
                        },
                        new
                        {
                            Id = 8,
                            Country = "Canada",
                            Name = "Plan B Games"
                        },
                        new
                        {
                            Id = 9,
                            Country = "USA",
                            Name = "Z-Man Games"
                        },
                        new
                        {
                            Id = 10,
                            Country = "Italy",
                            Name = "Horrible Guild"
                        });
                });

            modelBuilder.Entity("BoardGameLogger.Data.Models.BoardGame", b =>
                {
                    b.HasOne("BoardGameLogger.Data.Models.Publisher", "Publisher")
                        .WithMany("BoardGames")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("BoardGameLogger.Data.Models.LoanLog", b =>
                {
                    b.HasOne("BoardGameLogger.Data.Models.BoardGame", "BoardGame")
                        .WithMany("LoanLogs")
                        .HasForeignKey("BoardGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardGame");
                });

            modelBuilder.Entity("BoardGameLogger.Data.Models.BoardGame", b =>
                {
                    b.Navigation("LoanLogs");
                });

            modelBuilder.Entity("BoardGameLogger.Data.Models.Publisher", b =>
                {
                    b.Navigation("BoardGames");
                });
#pragma warning restore 612, 618
        }
    }
}
